version: "2"
services:
    mariadb:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=itda310
            - MYSQL_DATABASE=employees
        ports:
            - 3306:3306
        volumes:
            - database:/var/lib/mysql
    frontend:
        image: webdevops/php-nginx
        ports:
            - 8000:80
        volumes:
            - ./app/:/app/
        links:
            - mariadb
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        restart: always
        ports:
            - 8080:80
        volumes:
            - /sessions
        links:
            - mariadb
volumes:
    database: {}
